-- PeAS document classification v2
--
-- Research agendas, topics, and keywords have deliberately separate
-- vocabularies and document-association tables.  This migration is additive
-- and idempotent so it can be applied safely to existing installations.

ALTER TABLE public.research_agenda
  ALTER COLUMN name TYPE VARCHAR(255);

ALTER TABLE public.research_agenda
  ADD COLUMN IF NOT EXISTS code VARCHAR(32),
  ADD COLUMN IF NOT EXISTS normalized_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS effective_from DATE,
  ADD COLUMN IF NOT EXISTS effective_to DATE,
  ADD COLUMN IF NOT EXISTS is_official BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE public.research_agenda
SET normalized_name = LOWER(REGEXP_REPLACE(BTRIM(name), '[[:space:]]+', ' ', 'g'))
WHERE normalized_name IS NULL;

ALTER TABLE public.document_research_agenda
  ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS assigned_by VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS research_agenda_official_code_uidx
  ON public.research_agenda (code);

CREATE UNIQUE INDEX IF NOT EXISTS research_agenda_official_name_uidx
  ON public.research_agenda (normalized_name)
  WHERE is_official = TRUE;

CREATE INDEX IF NOT EXISTS research_agenda_active_order_idx
  ON public.research_agenda (is_active, sort_order, id);

CREATE UNIQUE INDEX IF NOT EXISTS document_research_agenda_primary_uidx
  ON public.document_research_agenda (document_id)
  WHERE is_primary = TRUE;

CREATE TABLE IF NOT EXISTS public.topics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  normalized_name VARCHAR(120) NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  proposed_by VARCHAR(255),
  reviewed_by VARCHAR(255),
  reviewed_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topics_status_check CHECK (status IN ('pending', 'approved', 'retired'))
);

CREATE UNIQUE INDEX IF NOT EXISTS topics_normalized_name_uidx
  ON public.topics (normalized_name);

CREATE INDEX IF NOT EXISTS topics_status_name_idx
  ON public.topics (status, normalized_name);

CREATE TABLE IF NOT EXISTS public.document_topics (
  document_id INTEGER NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  topic_id INTEGER NOT NULL REFERENCES public.topics(id) ON DELETE RESTRICT,
  topic_order INTEGER NOT NULL DEFAULT 1,
  assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_by VARCHAR(255),
  PRIMARY KEY (document_id, topic_id)
);

CREATE INDEX IF NOT EXISTS document_topics_topic_idx
  ON public.document_topics (topic_id, document_id);

CREATE TABLE IF NOT EXISTS public.keywords (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term VARCHAR(80) NOT NULL,
  normalized_term VARCHAR(80) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT keywords_term_length_check CHECK (char_length(BTRIM(term)) BETWEEN 2 AND 80)
);

CREATE UNIQUE INDEX IF NOT EXISTS keywords_normalized_term_uidx
  ON public.keywords (normalized_term);

CREATE TABLE IF NOT EXISTS public.document_keywords (
  document_id INTEGER NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  keyword_id INTEGER NOT NULL REFERENCES public.keywords(id) ON DELETE RESTRICT,
  keyword_order INTEGER NOT NULL DEFAULT 1,
  assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_by VARCHAR(255),
  PRIMARY KEY (document_id, keyword_id)
);

CREATE INDEX IF NOT EXISTS document_keywords_keyword_idx
  ON public.document_keywords (keyword_id, document_id);

CREATE TABLE IF NOT EXISTS public.classification_migration_review (
  document_id INTEGER NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  legacy_research_agenda_id INTEGER NOT NULL REFERENCES public.research_agenda(id) ON DELETE RESTRICT,
  legacy_value VARCHAR(255) NOT NULL,
  suggested_type VARCHAR(20),
  decision VARCHAR(20),
  target_id INTEGER,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  reviewed_by VARCHAR(255),
  reviewed_at TIMESTAMP WITHOUT TIME ZONE,
  notes TEXT,
  PRIMARY KEY (document_id, legacy_research_agenda_id),
  CONSTRAINT classification_review_suggested_type_check CHECK (suggested_type IS NULL OR suggested_type IN ('agenda', 'topic', 'keyword', 'discard')),
  CONSTRAINT classification_review_decision_check CHECK (decision IS NULL OR decision IN ('agenda', 'topic', 'keyword', 'discard')),
  CONSTRAINT classification_review_status_check CHECK (status IN ('pending', 'resolved'))
);

CREATE INDEX IF NOT EXISTS classification_review_status_idx
  ON public.classification_migration_review (status, document_id);

-- Official institutional research priorities.  Codes are stable identifiers;
-- display names may be edited later without changing document associations.
INSERT INTO public.research_agenda
  (code, name, normalized_name, is_official, is_active, sort_order)
VALUES
  ('RA-01', 'Paulinian Spirituality/Identity and its impact to international community and global partnerships', LOWER(REGEXP_REPLACE(BTRIM('Paulinian Spirituality/Identity and its impact to international community and global partnerships'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 1),
  ('RA-02', 'Paulinian Mission / Vision / Philosophy / Goals', LOWER(REGEXP_REPLACE(BTRIM('Paulinian Mission / Vision / Philosophy / Goals'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 2),
  ('RA-03', 'Paulinian Roots and Formation', LOWER(REGEXP_REPLACE(BTRIM('Paulinian Roots and Formation'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 3),
  ('RA-04', 'Advocacy (Peace, Pro-Life, Environment, Disaster & Risks Management)', LOWER(REGEXP_REPLACE(BTRIM('Advocacy (Peace, Pro-Life, Environment, Disaster & Risks Management)'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 4),
  ('RA-05', 'Global Mental Health and Wellness', LOWER(REGEXP_REPLACE(BTRIM('Global Mental Health and Wellness'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 5),
  ('RA-06', 'Synodal Church: Communion, Participation, and Mission', LOWER(REGEXP_REPLACE(BTRIM('Synodal Church: Communion, Participation, and Mission'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 6),
  ('RA-07', 'Inclusivity and Equity in Education', LOWER(REGEXP_REPLACE(BTRIM('Inclusivity and Equity in Education'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 7),
  ('RA-08', 'Curriculum development and Innovation geared towards internalization and global partnership', LOWER(REGEXP_REPLACE(BTRIM('Curriculum development and Innovation geared towards internalization and global partnership'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 8),
  ('RA-09', 'OBE - Instruction', LOWER(REGEXP_REPLACE(BTRIM('OBE - Instruction'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 9),
  ('RA-10', 'Technology Integration', LOWER(REGEXP_REPLACE(BTRIM('Technology Integration'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 10),
  ('RA-11', 'Faculty / Staff Development', LOWER(REGEXP_REPLACE(BTRIM('Faculty / Staff Development'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 11),
  ('RA-12', 'Infrastructure / Software Development and Innovation', LOWER(REGEXP_REPLACE(BTRIM('Infrastructure / Software Development and Innovation'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 12),
  ('RA-13', 'Financial Management, Sustainability, and Energy Security', LOWER(REGEXP_REPLACE(BTRIM('Financial Management, Sustainability, and Energy Security'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 13),
  ('RA-14', 'Environmental Discipline and Stewardship', LOWER(REGEXP_REPLACE(BTRIM('Environmental Discipline and Stewardship'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 14),
  ('RA-15', 'Ethical Leaders & Professionals', LOWER(REGEXP_REPLACE(BTRIM('Ethical Leaders & Professionals'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 15),
  ('RA-16', 'Cutting-edge Resilient Visionaries & Innovators; Engaging, Trustworthy Team Builders & Mentors; Reliable, Productive Experts & Implementers; Dedicated, Transformative Supporters & Stewardship in context of international community and global partnerships', LOWER(REGEXP_REPLACE(BTRIM('Cutting-edge Resilient Visionaries & Innovators; Engaging, Trustworthy Team Builders & Mentors; Reliable, Productive Experts & Implementers; Dedicated, Transformative Supporters & Stewardship in context of international community and global partnerships'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 16),
  ('RA-17', 'Civic and Community Involvement', LOWER(REGEXP_REPLACE(BTRIM('Civic and Community Involvement'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 17),
  ('RA-18', 'Equality and Diversity', LOWER(REGEXP_REPLACE(BTRIM('Equality and Diversity'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 18),
  ('RA-19', 'Economic cooperation and integration', LOWER(REGEXP_REPLACE(BTRIM('Economic cooperation and integration'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 19),
  ('RA-20', 'Student and Faculty Mobility', LOWER(REGEXP_REPLACE(BTRIM('Student and Faculty Mobility'), '[[:space:]]+', ' ', 'g')), TRUE, TRUE, 20)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  normalized_name = EXCLUDED.normalized_name,
  is_official = TRUE,
  is_active = TRUE,
  sort_order = EXCLUDED.sort_order,
  updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE FUNCTION public.peas_validate_document_classification_overlap()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_document_id INTEGER;
BEGIN
  target_document_id := COALESCE(NEW.document_id, OLD.document_id);

  IF EXISTS (
    SELECT 1
    FROM public.document_research_agenda dra
    JOIN public.research_agenda ra ON ra.id = dra.research_agenda_id
    JOIN public.document_topics dt ON dt.document_id = dra.document_id
    JOIN public.topics t ON t.id = dt.topic_id
    WHERE dra.document_id = target_document_id
      AND ra.normalized_name = t.normalized_name
  ) OR EXISTS (
    SELECT 1
    FROM public.document_research_agenda dra
    JOIN public.research_agenda ra ON ra.id = dra.research_agenda_id
    JOIN public.document_keywords dk ON dk.document_id = dra.document_id
    JOIN public.keywords k ON k.id = dk.keyword_id
    WHERE dra.document_id = target_document_id
      AND ra.normalized_name = k.normalized_term
  ) OR EXISTS (
    SELECT 1
    FROM public.document_topics dt
    JOIN public.topics t ON t.id = dt.topic_id
    JOIN public.document_keywords dk ON dk.document_id = dt.document_id
    JOIN public.keywords k ON k.id = dk.keyword_id
    WHERE dt.document_id = target_document_id
      AND t.normalized_name = k.normalized_term
  ) THEN
    RAISE EXCEPTION 'A document cannot reuse the same normalized term across research agenda, topic, and keyword classifications'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'peas_classification_overlap_agenda_trigger') THEN
    CREATE CONSTRAINT TRIGGER peas_classification_overlap_agenda_trigger
      AFTER INSERT OR UPDATE OR DELETE ON public.document_research_agenda
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.peas_validate_document_classification_overlap();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'peas_classification_overlap_topic_trigger') THEN
    CREATE CONSTRAINT TRIGGER peas_classification_overlap_topic_trigger
      AFTER INSERT OR UPDATE OR DELETE ON public.document_topics
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.peas_validate_document_classification_overlap();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'peas_classification_overlap_keyword_trigger') THEN
    CREATE CONSTRAINT TRIGGER peas_classification_overlap_keyword_trigger
      AFTER INSERT OR UPDATE OR DELETE ON public.document_keywords
      DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.peas_validate_document_classification_overlap();
  END IF;
END;
$$;
